version: '3.4'

services:
  it_helpdesk:
    ports:
        - 80:80
    image: ${DOCKER_REGISTRY-}ithelpdesk
    build:
      context: .
      dockerfile: IT_Helpdesk/Dockerfile

  maintenance_helpdesk:
    ports:
        - 81:80
    image: ${DOCKER_REGISTRY-}maintenancehelpdesk
    build:
      context: .
      dockerfile: Maintenance_Helpdesk/Dockerfile

