version: '3.4'

services:
  maintenance_helpdesk:
    ports:
        - 80:5001
    image: ${DOCKER_REGISTRY-}maintenancehelpdesk
    build:
      context: .
      dockerfile: Maintenance_Helpdesk/Dockerfile
  it_helpdesk:
    ports:
        - 81:5000
    image: ${DOCKER_REGISTRY-}ithelpdesk
    build:
      context: .
      dockerfile: IT_Helpdesk/Dockerfile